[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font]
size = 17

[window]
option_as_alt = "Both"
[keyboard]
bindings = [ { key = "Return", mods = "Shift", chars = "\n" } ]


[env]
TERM = "xterm-256color"
